### ISSUE TITLE
ray status - Ray cluster is not found

### ISSUE THREAD

**Issue by tekumara** [tekumara/ray-demo#2]
```
❯ make status
.venv/bin/ray status --address localhost:6379
Traceback (most recent call last):
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/_private/gcs_utils.py", line 120, in check_health
    resp = stub.CheckAlive(req, timeout=timeout)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = ""
        debug_error_string = "{"created":"@1671696158.922229624","description":"Error received from peer ipv4:10.97.36.20:6379","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"","grpc_status":12}"
>
Ray cluster is not found at 10.97.36.20:6379
make: *** [Makefile:49: status] Error 1
```

**Comment by tekumara** [comment]
ray cluster head node 2.2.0 with ray client 2.0.0

Upgrading the client to 2.2.0 resolved the issue.
