### ISSUE TITLE
Some processes that the driver needs to connect to have not registered with GCS

### ISSUE THREAD

**Issue by tekumara** [tekumara/ray-demo#3]
```
python -m rayexample.tf_mnist --address localhost:6379
2022-12-23 05:45:04.388521: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-23 05:45:06.019001: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/extras/CUPTI/lib64:
2022-12-23 05:45:06.019288: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/extras/CUPTI/lib64:
2022-12-23 05:45:06.019318: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
/home/compute/code/ray-demo/rayexample/tf_mnist.py:12: DeprecationWarning: The module `ray.air.callbacks.keras` has been moved to `ray.air.integrations.keras` and the old location will be deprecated soon. Please adjust your imports to point to the new location. Example: Do a global search and replace `ray.air.callbacks.keras` with `ray.air.integrations.keras`.
  from ray.air.callbacks.keras import Callback as TrainReportCallback
2022-12-23 05:45:07,790 INFO worker.py:1356 -- Connecting to existing Ray cluster at address: 10.97.36.20:6379...
[2022-12-23 05:45:07,805 W 289557 289557] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2022-12-23 05:45:08,806 W 289557 289557] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2022-12-23 05:45:09,807 W 289557 289557] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2022-12-23 05:45:10,808 W 289557 289557] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2022-12-23 05:45:11,817 W 289557 289557] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2022-12-23 05:45:12,818 W 289557 289557] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2022-12-23 05:45:13,819 W 289557 289557] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2022-12-23 05:45:14,820 W 289557 289557] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2022-12-23 05:45:15,822 W 289557 289557] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2022-12-23 05:45:16,823 W 289557 289557] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/compute/code/ray-demo/rayexample/tf_mnist.py", line 123, in <module>
    ray.init(address=args.address)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/_private/worker.py", line 1501, in init
    _global_node = ray._private.node.Node(
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/_private/node.py", line 243, in __init__
    node_info = ray._private.services.get_node_to_connect_for_driver(
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/_private/services.py", line 444, in get_node_to_connect_for_driver
    return global_state.get_node_to_connect_for_driver(node_ip_address)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/_private/state.py", line 752, in get_node_to_connect_for_driver
    node_info_str = self.global_state_accessor.get_node_to_connect_for_driver(
  File "python/ray/includes/global_state_accessor.pxi", line 155, in ray._raylet.GlobalStateAccessor.get_node_to_connect_for_driver
RuntimeError: b"This node has an IP address of 10.97.36.20, and Ray expects this IP address to be either the GCS address or one of the Raylet addresses. Connected to GCS at 10.97.36.20 and found raylets at 10.42.1.39 but none of these match this node's IP 10.97.36.20. Are any of these actually a different IP address for the same node?You might need to provide --node-ip-address to specify the IP address that the head should use when sending to this node."
```

**Comment by tekumara** [comment]
```
❯ python -m rayexample.tf_mnist --address localhost:10001
2022-12-23 05:49:26.959977: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-23 05:49:28.046011: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/extras/CUPTI/lib64:
2022-12-23 05:49:28.046131: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/extras/CUPTI/lib64:
2022-12-23 05:49:28.046147: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
/home/compute/code/ray-demo/rayexample/tf_mnist.py:12: DeprecationWarning: The module `ray.air.callbacks.keras` has been moved to `ray.air.integrations.keras` and the old location will be deprecated soon. Please adjust your imports to point to the new location. Example: Do a global search and replace `ray.air.callbacks.keras` with `ray.air.integrations.keras`.
  from ray.air.callbacks.keras import Callback as TrainReportCallback
2022-12-23 05:49:29,487 INFO worker.py:1356 -- Connecting to existing Ray cluster at address: 10.97.36.20:10001...
2022-12-23 05:49:29,491 ERROR utils.py:1428 -- Internal KV Get failed
Traceback (most recent call last):
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/_private/utils.py", line 1415, in internal_kv_get_with_retry
    result = gcs_client.internal_kv_get(key, namespace)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/_private/gcs_utils.py", line 199, in wrapper
    return f(self, *args, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/_private/gcs_utils.py", line 291, in internal_kv_get
    reply = self._kv_stub.InternalKVGet(req, timeout=timeout)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "Method not found!"
        debug_error_string = "{"created":"@1671774569.490946753","description":"Error received from peer ipv4:10.97.36.20:10001","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Method not found!","grpc_status":12}"
```

**Comment by tekumara** [comment]
Use:
```
python -m rayexample.tf_mnist --address ray://localhost:10001
```
