### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by tekumara** [tekumara/ray-demo#4]
```
❯ python -m rayexample.tf_mnist --address ray://localhost:10001
2022-12-23 05:59:11.119527: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-23 05:59:12.454392: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/extras/CUPTI/lib64:
2022-12-23 05:59:12.454927: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/extras/CUPTI/lib64:
2022-12-23 05:59:12.454961: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
/home/compute/code/ray-demo/rayexample/tf_mnist.py:12: DeprecationWarning: The module `ray.air.callbacks.keras` has been moved to `ray.air.integrations.keras` and the old location will be deprecated soon. Please adjust your imports to point to the new location. Example: Do a global search and replace `ray.air.callbacks.keras` with `ray.air.integrations.keras`.
  from ray.air.callbacks.keras import Callback as TrainReportCallback
Put failed:
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/compute/code/ray-demo/rayexample/tf_mnist.py", line 124, in <module>
    train_tensorflow_mnist(
  File "/home/compute/code/ray-demo/rayexample/tf_mnist.py", line 86, in train_tensorflow_mnist
    results = trainer.fit()
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/train/base_trainer.py", line 352, in fit
    trainable = self.as_trainable()
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/train/base_trainer.py", line 508, in as_trainable
    return tune.with_parameters(trainable_cls, **base_config)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/tune/trainable/util.py", line 355, in with_parameters
    parameter_registry.put(prefix + k, v)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/tune/registry.py", line 229, in put
    self.flush()
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/tune/registry.py", line 241, in flush
    self.references[k] = ray.put(v)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/util/client/api.py", line 52, in put
    return self.worker.put(*args, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/util/client/worker.py", line 496, in put
    return self._put_pickled(data, client_ref_id, _owner)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/util/client/worker.py", line 510, in _put_pickled
    raise cloudpickle.loads(resp.error)
ModuleNotFoundError: No module named 'tensorflow'
```

**Comment by tekumara** [comment]
Pod image needs to contain tensorflow.

**Comment by tekumara** [comment]
Or connect to the cluster using [runtime_env](https://docs.ray.io/en/latest/ray-core/handling-dependencies.html#specifying-a-runtime-environment-per-job):
```python
ray.init(address=args.address, runtime_env={"pip": ["tensorflow~=2.11.0"]})
```

**Comment by tekumara** [comment]
Using `runtime_env` it takes about a minute to install tensorflow into a temporary venv on my cluster running in aws us-east-1:
```
2022-12-29 14:59:29,269	INFO utils.py:76 -- Run cmd[3] ['/tmp/ray/session_2022-12-29_14-55-48_909694_8/runtime_resources/pip/798524a6e69c7e6f5ff59c5f2f7fdae3da3c69c3/virtualenv/bin/python', '-m', 'pip', 'install', '--disable-pip-version-check', '--no-cache-dir', '-r', '/tmp/ray/session_2022-12-29_14-55-48_909694_8/runtime_resources/pip/798524a6e69c7e6f5ff59c5f2f7fdae3da3c69c3/requirements.txt']
2022-12-29 15:00:31,231	INFO utils.py:97 -- Output of cmd[3]: Collecting tensorflow~=2.11.0
```
