### ISSUE TITLE
TypeError: Descriptors cannot not be created directly

### ISSUE THREAD

**Issue by tekumara** [tekumara/ray-demo#5]
```
2022-12-23 06:43:22,678 ERROR worker.py:512 -- Failed to deserialize b'\x80\x05\x953\x02\x00\x00\x00\x00\x00\x00\x8c\x08builtins\x94\x8c\tTypeError\x94\x93\x94X\x0f\x02\x00\x00Descriptors cannot not be created directly.\nIf this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.\nIf you cannot immediately regenerate your protos, some other possible workarounds are:\n 1. Downgrade the protobuf package to 3.20.x or lower.\n 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).\n\nMore information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates\x94\x85\x94R\x94.'
Traceback (most recent call last):
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/util/client/worker.py", line 510, in _put_pickled
    raise cloudpickle.loads(resp.error)
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/compute/code/ray-demo/rayexample/tf_mnist.py", line 124, in <module>
    train_tensorflow_mnist(
  File "/home/compute/code/ray-demo/rayexample/tf_mnist.py", line 86, in train_tensorflow_mnist
    results = trainer.fit()
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/train/base_trainer.py", line 352, in fit
    trainable = self.as_trainable()
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/train/base_trainer.py", line 508, in as_trainable
    return tune.with_parameters(trainable_cls, **base_config)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/tune/trainable/util.py", line 355, in with_parameters
    parameter_registry.put(prefix + k, v)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/tune/registry.py", line 229, in put
    self.flush()
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/tune/registry.py", line 241, in flush
    self.references[k] = ray.put(v)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/util/client/api.py", line 52, in put
    return self.worker.put(*args, **kwargs)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/util/client/worker.py", line 496, in put
    return self._put_pickled(data, client_ref_id, _owner)
  File "/home/compute/code/ray-demo/.venv/lib/python3.9/site-packages/ray/util/client/worker.py", line 510, in _put_pickled
    raise cloudpickle.loads(resp.error)
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by tekumara** [comment]
```
❯ pip list | grep protobuf
protobuf                     3.19.6
```

**Comment by tekumara** [comment]
See https://github.com/ray-project/ray/issues/31309
